import { Alert, StyleSheet, Switch, Text, View } from 'react-native';
import { router } from 'expo-router';
import { Ionicons } from '@expo/vector-icons';
import { Button, Card, Header, IconButton, Screen, SectionTitle } from '@/components/ui';
import { colors, spacing, type } from '@/theme/tokens';
import { useAppStore } from '@/store/useAppStore';
import { useState } from 'react';

function ToggleRow({ icon, title, body, value, onValueChange }: { icon: keyof typeof Ionicons.glyphMap; title: string; body: string; value: boolean; onValueChange: (value: boolean) => void }) {
  return <View style={styles.toggle}><View style={styles.icon}><Ionicons name={icon} size={21} color={colors.forest} /></View><View style={{ flex: 1 }}><Text style={styles.title}>{title}</Text><Text style={styles.body}>{body}</Text></View><Switch value={value} onValueChange={onValueChange} trackColor={{ false: colors.border, true: colors.sage }} thumbColor={value ? colors.forestDeep : colors.white} /></View>;
}

export default function SettingsScreen() {
  const { resetData } = useAppStore();
  const [cycle, setCycle] = useState(true);
  const [analytics, setAnalytics] = useState(false);
  const [modelTraining, setModelTraining] = useState(false);
  return (
    <Screen>
      <IconButton icon="arrow-back" label="Go back" onPress={() => router.back()} />
      <Header eyebrow="Your data" title="Privacy & settings" subtitle="Control optional health inputs, integrations, export, and deletion." />
      <SectionTitle title="Consent" />
      <Card style={{ paddingVertical: spacing.xs }}>
        <ToggleRow icon="female-outline" title="Cycle-aware suggestions" body="Use symptoms and history—not phase assumptions—to adjust training." value={cycle} onValueChange={setCycle} />
        <View style={styles.border}><ToggleRow icon="stats-chart-outline" title="Sensitive-data analytics" body="Off by default; excludes health data from product analytics." value={analytics} onValueChange={setAnalytics} /></View>
        <View style={styles.border}><ToggleRow icon="sparkles-outline" title="Use my data for model training" body="Off by default. Deterministic planning still works." value={modelTraining} onValueChange={setModelTraining} /></View>
      </Card>
      <SectionTitle title="Data controls" />
      <Card><Button title="Export my data" variant="secondary" icon="download-outline" onPress={() => Alert.alert('Export prepared', 'A portable JSON export would be generated by the authenticated backend in production.')} /><View style={{ height: spacing.sm }} /><Button title="Manage connected services" variant="secondary" icon="link-outline" onPress={() => router.push('/integrations')} /></Card>
      <Card tone="peach"><Text style={styles.dangerTitle}>Delete account and data</Text><Text style={styles.body}>Permanently remove your account, health logs, plans, nutrition data, and stored integration tokens after re-authentication.</Text><View style={{ height: spacing.md }} /><Button title="Delete account and data" variant="danger" onPress={() => Alert.alert('Delete everything?', 'This action is permanent in production. For this local demo, it resets the app.', [{ text: 'Cancel', style: 'cancel' }, { text: 'Delete', style: 'destructive', onPress: () => { resetData(); router.replace('/'); } }])} /></Card>
      <Text style={styles.disclaimer}>Operational audit logs should retain only what is legally and operationally necessary, with restricted access and documented retention.</Text>
    </Screen>
  );
}

const styles = StyleSheet.create({ toggle: { flexDirection: 'row', alignItems: 'center', gap: spacing.md, paddingVertical: spacing.lg }, icon: { width: 40, height: 40, borderRadius: 20, backgroundColor: colors.sagePale, alignItems: 'center', justifyContent: 'center' }, title: { ...type.h3, color: colors.ink }, body: { ...type.small, color: colors.inkMuted, marginTop: 3 }, border: { borderTopWidth: 1, borderTopColor: colors.border }, dangerTitle: { ...type.h3, color: colors.red }, disclaimer: { ...type.small, color: colors.inkMuted, textAlign: 'center' } });

